language: erlang
otp_release:
    - 21.3
    - 22.1

script:
    - rebar3 check

cache:
    directories:
        - "$HOME/.cache/rebar3"

after_success:
   - curl -s https://codecov.io/bash > upload-coverage.sh
   - chmod +x upload-coverage.sh
   - ./upload-coverage.sh -v -s _build/test/cover -f '*.coverdata'
