language: erlang
otp_release:
    - 21.3
    - 22.1

script:
    - rebar3 check

cache:
    directories:
        - "$HOME/.cache/rebar3"

after_success:
   - bash <(curl -s https://codecov.io/bash) -f _build/test/cover/eunit.coverdata
   - bash <(curl -s https://codecov.io/bash) -f _build/test/cover/proper.coverdata
   - bash <(curl -s https://codecov.io/bash) -f _build/test/cover/ct.coverdata
