version: "{build}"
branches:
  only:
    - master
environment:
  matrix:
    - erlang_version: 21.2
    - erlang_version: 22.0
install:
  - ps: choco install erlang --version $env:erlang_version
  - ps: choco install rebar3
build:
  - parallel: true
build_script:
  - ps: rebar3 as prod tar -n mqtt_simulator
test_script:
  - ps: rebar3 check
cache:
  - '%USERPROFILE%\.cache\rebar3'
artifacts:
  - path: '**\*.tar.gz'
deploy:
  description: 'Windows Build'
  provider: GitHub
  auth_token:
    secure: x/8ybde3PJqvqqzYoPub55aCdrER45ZAkAGetkBBibumWvv7WFLJXkDiRRmJDdxr
  artifact: /.*\.tar\.gz
  draft: false
  prerelease: false
  force_update: true
  on:
    # release from master branch only
    branch: master
    # deploy on tag push only
    APPVEYOR_REPO_TAG: true
