version: "{build}"
branches:
  only:
  - master
environment:
  matrix:
  - erlang_version: 21.3
  - erlang_version: 22.1
install:
- ps: choco install erlang --version $env:erlang_vsn
- ps: choco install rebar3
build_script:
- ps: rebar3 as prod release -n mqtt_simulator
test_script:
- ps: rebar3 check
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
